### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by henninghaakonsen** [pqina/filepond-plugin-file-validate-type#15]
Would it be possible to add typescript support to the plugins so that the options/props are available from <Filepond />?

**Comment by rikschennink** [comment]
I don't have a lot of experience with typescript so I don't know. As the plugins extend the options on the core FilePond library I wonder if this is possible.

**Comment by joelbourbon** [comment]
The type would look like this:
```
export interface IFilepondPluginFileValidateTypeProps {
  /** Enable or disable file type validation. */
  allowFileTypeValidation?: boolean
  /** Array of accepted file types. Can be mime types or wild cards. For instance ['image/*'] will accept all images. ['image/png', 'image/jpeg'] will only accepts PNGs and JPEGs. */
  acceptedFileTypes?: string[]
  /** Message shown when an invalid file is added. */
  labelFileTypeNotAllowed?: string
  /** Message shown to indicate the allowed file types. Available placeholders are {allTypes}, {allButLastType}, {lastType}. */
  fileValidateTypeLabelExpectedTypes?: string
  /** Allows mapping the file type to a more visually appealing label, { 'image/jpeg': '.jpg' } will show .jpg in the expected types label. Set to null to hide a type from the label. */
  fileValidateTypeLabelExpectedTypesMap?: object
  /** A function that receives a file and the type detected by FilePond, should return a Promise, resolve with detected file type, reject if can’t detect. */
  fileValidateTypeDetectType?: (file: File, type: string) => Promise<string>
}
```

Not sure if it would make sense to deploy on the side or to insert it within the main package.
For now, I am using the above within my project to validate my options & add intellisense to developers.

**Comment by rikschennink** [comment]
Thanks I'll consider doing that.

**Comment by muzamuba** [comment]
I am unable to get it work

**Comment by muzamuba** [comment]
@joelbourbon I have tried to use your example but I am getting typescript error when I use 'filepond-plugin-file-validate-type' plugin props in my class. Here is the description of the error

Property 'labelFileTypeNotAllowed' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FilePond> & Readonly<FilePondProps> & Readonly<{ children?: ReactNode; }>'.  TS2322.

Can you help me in resolving the issue ? 
Thank you

[Attachment.txt](https://github.com/pqina/filepond-plugin-file-validate-type/files/3406159/Attachment.txt)

**Comment by chrispaynter** [comment]
@muzamuba yep it's a bit of a hassle getting typing working correctly with Filepond and plugins, but I think the solution here will help you.

I use many of the file-pond plugins, and the following pattern works for me to make them play nice with Typescript. I'll strip it back and show you how to get a single file pond plugin working with TS.

**Put your custom typings somewhere**
You'll need to create some manual typings in your project. I use Create React App and have created a folder in my src folder. The path is `src/typings`

## Step 1: Create types for the plugins you want to use
Inside the typings folder I created a folder named exactly as each of the plugins I use, and create an `index.d.ts` file inside.

For example, I have this file `src/typings/filepond-plugin-file-validate-size/index.d.ts` and inside that I have this

```
declare module 'filepond-plugin-file-validate-size' {
  const FilePondPluginFileValidateSize: any;
  export default FilePondPluginFileValidateSize;
}
```

Bit of a yuck `any` type in there, but I'll address that later. Anyway...

This will resolve your typing issues for importing *the plugin modules*. _But_ you will then need to extend Filepond so that you can use the module specific properties directly on your <FilePond /> component, in order to activate and configure them.

## Step 2: Extend FilePond's types to include the plugin specific props
Create a file `src/typings/react-filepond/index.d.ts`, and then use the following code as a template:

```
import * as ReactFilePond from 'react-filepond';
declare module 'react-filepond' {
  export interface FilePondProps {
    // filepond-plugin-file-validate-size PROPS
    allowFileSizeValidation?: boolean;
    maxFileSize?: string;

   // Add any other plugins you need in the same way
  }
}

```

This will import the base types from `@types/react-filepond` so we don't have to redeclare them, and then extend them with our own decleration of the module. In that declaration we put the custom props required for the file pond modules.

Sorry I'm a bit rammed on a project and perhaps haven't written as succinct answer as much as I'd usually like to, but this has just worked for me and I hope it can help unblock you 🙏

**Comment by rikschennink** [comment]
@chrispaynter hi Chris, we’re working on this here https://github.com/pqina/filepond/pull/362

**Comment by chrispaynter** [comment]
Thanks @rikschennink, subscribed to the thread.

**Comment by muzamuba** [comment]
Thanks alot for the feedback @chrispaynter

**Comment by caribouflex** [comment]
Hi everyone, I see this issue is still open. However the PR @rikschennink mention is resolved. I'm currently doing something similar that @chrispaynter was saying. I was just wondering if something to handle plugins type was integrated with filepond ?

**Comment by rikschennink** [comment]
@caribouflex not yet, happy to accept types for plugins as well but they should be added to each plugin repo separately.

**Comment by caribouflex** [comment]
@rikschennink that make sense. Thanks for the clarification :ok_hand:

**Comment by nt4f04uNd** [comment]
is this issue dead

**Comment by rikschennink** [comment]
@nt4f04uNd 
> is this issue dead

I think so because typescript support has been added a while ago:
https://github.com/pqina/filepond-plugin-file-validate-type/tree/master/types
