### ISSUE TITLE
Type validation by comparing against magic numbers

### ISSUE THREAD

**Issue by akoury** [pqina/filepond-plugin-file-validate-type#3]
Hello,

First of all, I would like to thank you on building such a great product, it has been working great for me this far.

One small issue I've encountered is on file type validation, from what I can tell by reading the source the validation is done by reading the file type attribute and the extension in the name, however, this can cause false positives, if for example, a user has a virus.exe file and changes it to virus.png, it will pass image validation.

Searching the web I found that the most commonly used method to protect against this is by comparing against magic numbers that actually tell you which type the file is.

[https://stackoverflow.com/questions/18299806/how-to-check-file-mime-type-with-javascript-before-upload/29672957#29672957](url) explains the issue better

I found this [library](https://github.com/sindresorhus/file-type) which supports checking against many many file types and their corresponding magic numbers, so I think it would be great if this could be added to the type validation as another step. I would be happy to help in any way possible.

Thanks!

**Comment by rikschennink** [comment]
Hi!

File type validation is done with using the file object `type` property which returns a mime/type, unfortunately, that is indeed based on the extension ( as far as I tell this differs per browser as each browser might have a different extension to mime/type table ).

I like the idea, however reading the StackOverflow post I notice that for instance, jpeg, is not as easy detected as it seems. We also have to deal with non-image mime/types, can they also be read from the header I wonder? Instead of the mime/types you could set the required header "magic numbers" and then map them to extensions using the `fileValidateTypeLabelExpectedTypesMap`. That way this functionality could maybe be covered with a basic method that reads the file header ( if that's enough for all file formats ). Another concern is that additional scanning on the server is still necessary to be sure someone didn't alter the client in any way. It's a cost/benefit thing for me, if we can keep this very small and fast then a lightweight check is nice. But if it means the package size grows by a lot, or validation becomes slow for big files, while we still have to do server-side checks, that would be wasteful.

**Comment by akoury** [comment]
The library I mentioned contains magic numbers for 81 file types including pdf, zip, mp3, mp4, exe, woff, sqlite, etc.

It seems the numbers are constantly updated, that is why I mentioned that it could be useful to use the library directly as a dependency, not having to keep a copy of the magic numbers in this library.

I agree on the performance analysis you make, if it is too costly it would not be beneficial, however if it is not then I believe it would greatly improve the functionality, sadly I have no way of telling how performance would be impacted.

**Comment by rikschennink** [comment]
Oh, I missed the library link :) Thanks!

**Comment by rikschennink** [comment]
I think this is solved with the new `fileValidateTypeDetectType` property with which you can manually determine the type (you could add the file type library in that method).
https://pqina.nl/filepond/docs/patterns/plugins/file-validate-type/
